//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStates
    {
        public int ID { get; set; }
        public int state_ID { get; set; }
        public int UnderReviewNotes { get; set; }
        public int PublishedNotes { get; set; }
        public int DownloadedNotes { get; set; }
        public int TotalExpenses { get; set; }
        public int TotalEarnings { get; set; }
        public int BuyerRequests { get; set; }
        public int SoldNotes { get; set; }
        public int RejectedNotes { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
